"""Render inputs/, expected/ and traptask.yaml from gold.cases.json.

Validate first, then write: a case set that fails validation should not leave a
half-written task behind. traptask.yaml is generated here rather than
hand-maintained, because in the task this one replaces it drifted -- it still
described twenty single-cell lookups after the questions had become multi-hop.

    python3 build_cases.py
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

HERE = Path(__file__).parent
GOLD = json.loads((HERE / "gold.cases.json").read_text())
KNOWN_MATCHERS = {"committed_value", "committed_has_value", "committed_regex",
                  "regex_required",
                  "no_hedge", "not_derivable"}


def validate() -> list[dict]:
    cases = GOLD["cases"]
    doc = HERE / GOLD["document"]
    if not doc.exists():
        raise SystemExit(f"document missing: {doc} -- run build_document.py first")

    ids = [c["id"] for c in cases]
    if len(set(ids)) != len(ids):
        raise SystemExit("duplicate case ids")

    geometry = json.loads((HERE / "gold_geometry.json").read_text())
    for c in cases:
        for field in ("id", "question", "answer", "matchers", "_why", "type", "difficulty"):
            if not c.get(field):
                raise SystemExit(f"{c['id']}: missing {field}")
        if "ANSWER:" not in c["question"]:
            raise SystemExit(f"{c['id']}: question does not state the answer contract")
        for m in c["matchers"]:
            if m["kind"] not in KNOWN_MATCHERS:
                raise SystemExit(f"{c['id']}: unknown matcher {m['kind']}")
        if c.get("figure") and c["figure"] not in geometry:
            raise SystemExit(f"{c['id']}: figure {c['figure']} is not in gold_geometry.json")
    return cases


def render(cases: list[dict]) -> None:
    for d in ("inputs", "expected"):
        shutil.rmtree(HERE / d, ignore_errors=True)
    doc = HERE / GOLD["document"]

    for c in cases:
        in_dir = HERE / "inputs" / c["id"]
        exp_dir = HERE / "expected" / c["id"]
        in_dir.mkdir(parents=True)
        exp_dir.mkdir(parents=True)
        shutil.copyfile(doc, in_dir / "document.pdf")
        (in_dir / "question.txt").write_text(c["question"] + "\n")
        (exp_dir / "answer.json").write_text(json.dumps({
            "answer": c["answer"],
            "figure": c.get("figure"),
            "panel": c.get("panel"),
            "type": c["type"],
            "difficulty": c["difficulty"],
            "matchers": c["matchers"],
        }, indent=2, ensure_ascii=False) + "\n")

    lines = [
        "# Generated by build_cases.py from gold.cases.json. Do not hand-edit.",
        "dirs:",
        "  inputs: inputs/",
        "  expected: expected/",
        "",
        "cases:",
    ]
    for c in cases:
        desc = f"{c['figure'].replace('figure_', 'figure ')}, {c['panel']}: {c['type'].replace('_', ' ')}"
        lines += [
            f"- id: {c['id']}",
            f'  description: "{desc}"',
            f"  tags: [{c['type']}, {c['difficulty']}]",
        ]
    lines += ["", "judge:", "  cmd: python3 judge.py", "", "grader:", "  cmd: python3 grader.py", ""]
    (HERE / "traptask.yaml").write_text("\n".join(lines))


if __name__ == "__main__":
    cases = validate()
    render(cases)
    print(f"rendered {len(cases)} cases, traptask.yaml regenerated")
