"""Generate gold.cases.json -- the case grid -- from scenarios.json.

The grid is scenario x stack_level x overlap_class. L0 is the shared baseline:
nothing has been added yet, so the two arms are identical there and share a
single case rather than duplicating one.

    L0                      -> 1 case per scenario
    L1, L2, L3 x {high,low} -> 6 cases per scenario
                               = 7 cases per scenario

gold.cases.json holds only the grid. The catalog itself is composed at build
time from catalog.json, so a schema edit never has to be applied in 42 places.

Run: python3 gen_grid.py   (committed output; rarely needed)
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent

LEVELS = ["L1", "L2", "L3", "L4"]
ARMS = ["high", "low"]


def main() -> None:
    scenarios = json.loads((HERE / "scenarios.json").read_text())["scenarios"]

    cases = []
    for sc in scenarios:
        cases.append({"scenario": sc["id"], "stack_level": "L0", "overlap_class": "none"})
        for level in LEVELS:
            for arm in ARMS:
                cases.append({"scenario": sc["id"], "stack_level": level, "overlap_class": arm})

    for i, c in enumerate(cases, start=1):
        c["id"] = f"case_{i:02d}"

    # id first, for readability
    cases = [{"id": c["id"], **{k: v for k, v in c.items() if k != "id"}} for c in cases]

    out = {
        "_doc": (
            "GENERATED by gen_grid.py from scenarios.json -- do not hand-edit. The grid is "
            "scenario x stack_level x overlap_class, with L0 shared between the two arms. "
            "Case content (the skill catalog, the request, the expected calls) is composed at "
            "build time from catalog.json + scenarios.json; only the grid lives here. Case IDs "
            "are opaque on purpose: a solution can read its own inputs_dir path, so an ID like "
            "s04_high_L3 would hand it the condition it is in."
        ),
        "cases": cases,
    }
    (HERE / "gold.cases.json").write_text(json.dumps(out, indent=2) + "\n")

    # traptask.yaml is emitted from the same loop rather than maintained by
    # hand: a case list that drifts out of sync with gold.cases.json is a real
    # copy-paste mistake that validate_task.py exists to catch, and generating
    # both from one source makes it impossible.
    labels = {s["id"]: s["label"] for s in scenarios}
    labels_difficulty = {s["id"]: s["difficulty"] for s in scenarios}
    lines = [
        "# GENERATED by gen_grid.py -- do not hand-edit; edit scenarios.json and re-run.",
        "dirs:",
        "  inputs: inputs/",
        "  expected: expected/",
        "",
        "cases:",
    ]
    for c in cases:
        sc, lvl, arm = c["scenario"], c["stack_level"], c["overlap_class"]
        if lvl == "L0":
            where = "baseline, nothing added"
        elif lvl == "L4":
            where = f"{arm}-overlap skills plus ~100 unrelated fillers in both arms"
        else:
            where = f"{arm}-overlap skills added"
        lines.append(f'- id: {c["id"]}')
        lines.append(f'  description: "{labels[sc]} — {lvl}, {where}"')
        tier = labels_difficulty[sc]
        lines.append(f'  tags: [office_automation, scenario:{sc}, difficulty:{tier}, '
                     f'stack_level:{lvl}, overlap_class:{arm}]')
    lines += ["", "judge:", "  cmd: python3 judge.py", "", "grader:", "  cmd: python3 grader.py", ""]
    (HERE / "traptask.yaml").write_text("\n".join(lines))

    print(f"Wrote gold.cases.json and traptask.yaml with {len(cases)} cases "
          f"({len(scenarios)} scenarios x {1 + len(LEVELS) * len(ARMS)} variants).")


if __name__ == "__main__":
    main()
